begin: use_linked_list.o linked_list.o
	gcc -Wall -o  linked_list.o use_linked_list.o

linked_list.o: linked_list.h linked_list.c

use_linked_list.o: linked_list.h use_linked_list.c

clean:
	rm -f begin *.o 

